application: streamspigot
version: 1
runtime: python
api_version: 1

builtins:
- appstats: on

handlers:
- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: .*
  script: main.py

