/* eslint-disable */
// Generated by Wrangler by running `wrangler types worker-configuration.d.ts --config wrangler.types.toml --env-file worker-types.env --include-runtime false` (hash: f5eb522293f676a6312c5b2749f9fe88)
interface __BaseEnv_Env {
	STREAMSPIGOT: KVNamespace;
	ASSETS: Fetcher;
	SKY_OAUTH_LOCK: DurableObjectNamespace /* SkyOAuthLock */;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
