/* eslint-disable */
// Generated by Wrangler by running `wrangler types worker-configuration.d.ts --config wrangler.types.toml --env-file worker-types.env --include-runtime false` (hash: 1e1e094db1d35841e8698bb1a4aaaad3)
declare namespace Cloudflare {
	interface Env {
		STREAMSPIGOT: KVNamespace;
		ASSETS: Fetcher;
	}
}
interface Env extends Cloudflare.Env {}
