/* eslint-disable */
// Generated by Wrangler by running `wrangler types worker-configuration.d.ts --config wrangler.types.toml --env-file worker-types.env --include-runtime false` (hash: 4ccc7a24601244e532a0c47d5845028a)
interface __BaseEnv_Env {
	STREAMSPIGOT: KVNamespace;
	ASSETS: Fetcher;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
