"$schema" = "./node_modules/wrangler/config-schema.json"
name = "streamspigot"
account_id = "2ccb840de076261467812cbc32f8aa47"
workers_dev = true
compatibility_date = "2026-05-14"
compatibility_flags = ["nodejs_als", "nodejs_compat"]

main = ".svelte-kit/cloudflare/_worker.js"

[assets]
directory = ".svelte-kit/cloudflare"
binding = "ASSETS"

[[kv_namespaces]]
binding = "STREAMSPIGOT"
id = "0d58678cdea94a018dc79669f6bc9a76"

[observability]
enabled = true
head_sampling_rate = 1
