name = "streamspigot"
account_id = "2ccb840de076261467812cbc32f8aa47"
workers_dev = true
compatibility_date = "2024-04-13"

main = "./.cloudflare/worker.js"
assets.directory = ".cloudflare/public"
assets.binding = "ASSETS"

build.command = "npm run build"

[[kv_namespaces]]
binding = "MASTOFEEDER"
id = "0d58678cdea94a018dc79669f6bc9a76"

[dev]
port = 5413

[observability]
enabled = true
head_sampling_rate = 1
